<?php

use PHPUnit\Framework\TestCase;
use Dykyi\Models\Hotels;

/**
 * Class HotelsTest
 *
 * @coversDefaultClass Hotels
 */
class HotelsTest extends TestCase
{
    /** @var Hotels */
    private $hotels;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->hotels = new Hotels();
    }

    /**
     * @covers ::getRandomHotelName
     */
    public function testGetHotelsName()
    {
        $this->assertNotEmpty($this->hotels->getRandomHotelName());
    }

    /**
     * @covers ::getHotelCoordinatesByName
     */
    public function testGetHotelsCoord()
    {
        $this->assertNotNull($this->hotels->getHotelCoordinatesByName('Amba Hotel Marble Arch'));
    }

}
