<?php

use PHPUnit\Framework\TestCase;
use Dykyi\Models\POIs;

/**
 * Class POIsTest
 *
 * @coversDefaultClass POIs
 */
class POIsTest extends TestCase
{
    /** @var POIs */
    private $pois;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pois = new POIs();
    }

    /**
     * @covers ::getPOIsByCoordinates
     */
    public function testGetPOIsByCoordinates()
    {
        $this->assertNotEmpty($this->pois->getPOIsByCoordinates());
    }

}
